[package]
name = "neurina"
version = "0.1.0"
authors = ["Łukasz Szpakowski <luckboy@vp.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owlchess = "0.4.0"
rand = "0.9"
unmtx-gpu = "0.1.2"
